# 2. Data Cleaning

- Notebook ini berfokus merapikan data sehingga dapat diolah
- Notebook ini TIDAK melakukan preprocessing yang merubah informasi dari data

Random insight note:
- Ada temp yang sampe lebih dari 100 awokwokwok, antara outlier atau jgn jgn farenheit
- 311945	1406998800	2014-08-02 17:00:00+00:00	28800	125.60	
-

In [55]:
import pandas as pd
import numpy as np
import re

In [56]:
df_train = pd.read_csv('./dataset/train.csv')
df_train['datetime_iso'] = pd.to_datetime(df_train['datetime_iso'])

df_test = pd.read_csv('./dataset/test.csv')
df_test['datetime_iso'] = pd.to_datetime(df_test['datetime_iso'])

In [57]:
df_test.head(50)

,datetime,datetime_iso,time-zone,temp,visibility,d_point,feels,min_temp,max_temp,prssr,sea_level,grnd_level,hum,wind_spd,wind_deg,rain_3h,snow_1h,snow_3h,clouds
0,1514764800,2018-01-01 00:00:00+00:00,28800,26.59 °C,NaN,23.66,26.59,26.02,27.16,1009,NaN,undetermined,84,1.45 m/s,355,0,NaN,no_snow,97
1,1514768400,2018-01-01 01:00:00+00:00,28800,26.51 C,NaN,24.92,26.51 °C,26.06,28.04,1009,NaN,undetermined,91,1.67 m/s,351,0mm,no-snow,0 milimeter,95
2,1514772000,2018-01-01 02:00:00+00:00,28800,28.68 C,NaN,25.71,34.68,28.03 C,29.3 C,1009.0 hPa.,NaN,NaN,84,1.72 m/s,345.0°,0 mm,volume:zero,0,90
3,1514775600,2018-01-01 03:00:00+00:00,28800,28.84 C,NaN,25.25,34.51,28.52,29.08 °C,1008,NaN,NaN,81,1.49,339.0°,0 milimeter,0,NaN,91
4,1514779200,2018-01-01 04:00:00+00:00,28800,29.75 Celcius,,24.62,35.38,29.31 C,30.57,1007,undetermined,undetermined,74,1.39 m/s,339.0°,NaN,0,volume:0,96
5,1514782800,2018-01-01 05:00:00+00:00,28800,30.09 C,NaN,26.88 Celcius,37.09,28.02,30.82 C,1006.0hPa,undetermined,undetermined,83,0.52 m/s,330,NaN,NaN,0,69
6,1514786400,2018-01-01 06:00:00+00:00,28800,30.38 °C,NaN,26.75,37.38,29.02,31.34 Celcius,1006,undetermined,undetermined,81,1.16 m/s,304.0 °,0,0,NaN,96
7,1514790000,2018-01-01 07:00:00+00:00,28800,30.55 C,NaN,25.83°C,37.55 C,26.02,31.66 C,1005.0 hPa,undetermined,undetermined,76,1.17,318,NaN,NaN,0mm,99.00%
8,1514793600,2018-01-01 08:00:00+00:00,28800,29.66 C,NaN,26.05 C,36.66,29.04,30.89,1005,undetermined,undetermined,81,0.31,318.0°,0,0,NaN,98
9,1514797200,2018-01-01 09:00:00+00:00,28800,29.31 C,NaN,26.52 C,36.31,27.92,30.21 C,1005,not-recorded,undetermined,85,0.68,112.0 °,zero,NaN,0,99
10,1514800800,2018-01-01 10:00:00+00:00,28800,26.79 C,NaN,25.2 C,30.23,26.14 Celcius,27.82 C,1005,undetermined,not_recorded,91,0.7 m/s,103,NaN,0,NaN,97
11,1514804400,2018-01-01 11:00:00+00:00,28800,26.51,NaN,25.28 Celcius,26.51,25.61,27.34 C,1006,NaN,undetermined,93,0.97,100,0,0,0,95
12,1514808000,2018-01-01 12:00:00+00:00,28800,26.76,NaN,25.53,30.33,25.89,27.59 C,1007.0 hPa.,NaN,NaN,93,1.03,79.0°,0,no_snow,NaN,91
13,1514811600,2018-01-01 13:00:00+00:00,28800,26.67 C,NaN,25.44 °C,30.06°C,25.75°C,27.37 C,1008,undetermined,NaN,93,1,42.0 °,0,NaN,NaN,96
14,1514815200,2018-01-01 14:00:00+00:00,28800,26.74°C,NaN,25.69,30.36 C,25.86 °C,27.39 C,1008,undetermined,NaN,94,1.05,21,NaN,0,no-snow,95
15,1514818800,2018-01-01 15:00:00+00:00,28800,25.96 C,NaN,25.1,25.96,25.43,26.71,1008,undetermined,undetermined,95,0.95 m/s,12.0 °,NaN,0,0,98
16,1514822400,2018-01-01 16:00:00+00:00,28800,25.64 C,NaN,24.95 C,26.77 C,24.95,26.19 C,1008,undetermined,NaN,96,0.76,359.0°,NaN,0,0,100
17,1514826000,2018-01-01 17:00:00+00:00,28800,25.15,NaN,24.47,26.23,24.33,26.05,1008,not recorded,not_recorded,96,0.67,319.0 °,NaN,NaN,volume:zero,100
18,1514829600,2018-01-01 18:00:00+00:00,28800,24.62,NaN,24.45 °C,25.72,23.94,26.04,1007.0 hPa,unknown,NaN,99,0.72m/s,274.0 °,0,0,0,100
19,1514833200,2018-01-01 19:00:00+00:00,28800,24.67 C,empty,24.33,25.75,24.06,26.04°C,1007,NaN,undetermined,98,0.94,259.0°,NaN,0,0,97
20,1514836800,2018-01-01 20:00:00+00:00,28800,24.09 C,NaN,23.58 C,25.09 °C,23.58 °C,26.04 C,1007,undetermined,not recorded,97,1.25m/s,273.0 °,NaN,0,nol,94.00%
21,1514840400,2018-01-01 21:00:00+00:00,28800,24.21 C,NaN,23.7 C,25.22,23.69,26.04 C,1007.0 hPa,NaN,not-recorded,97,1.3,270.0°,no_rain,NaN,0,79
22,1514844000,2018-01-01 22:00:00+00:00,28800,25.07 C,NaN,24.04,26.09 °C,24.53°C,26.04 C,1007,unknown,undetermined,94,1.35,288,NaN,NaN,0,97.00%
23,1514847600,2018-01-01 23:00:00+00:00,28800,25.29°C,NaN,24.25 C,26.33,24.68,27.04,1009.0 hPa,undetermined,NaN,94,1.06m/s,316.0 °,0mm,NaN,0,98
24,1514851200,2018-01-02 00:00:00+00:00,28800,25.53 C,NaN,24.49 °C,26.59,24.9,26.19 C,1009,undetermined,undetermined,94,0.97m/s,327,0,NaN,NaN,99
25,1514854800,2018-01-02 01:00:00+00:00,28800,26.01°C,unknown,24.43,26.01 C,24.02°C,26.44,1009,undetermined,undetermined,91,1.13,329.0 °,no_rain,zero,NaN,99
26,1514858400,2018-01-02 02:00:00+00:00,28800,28.95 C,NaN,24.51,33.97 °C,24.02,29.52,1009.0 hPa,NaN,undetermined,77.00%,1.54,313.0°,0,NaN,NaN,96
27,1514862000,2018-01-02 03:00:00+00:00,28800,29.66 C,NaN,24.98 C,35.63 C,25.02,30.35,1009,NaN,unestablished,76,2.07 m/s,293.0°,NaN,NaN,NaN,98
28,1514865600,2018-01-02 04:00:00+00:00,28800,30.34,NaN,24.49 C,36.14 C,26.02,31.1 C,1008,undetermined,undetermined,71,2.08,282,NaN,NaN,NaN,98
29,1514869200,2018-01-02 05:00:00+00:00,28800,29.93 C,NaN,23.86,34.87,27.02,30.28 C,1007,NaN,NaN,70,2.19,264,nol,nol,0,97
30,1514872800,2018-01-02 06:00:00+00:00,28800,30.55 C,NaN,25.16 °C,37.26 Celcius,28.02,30.96 C,1006,undetermined,undetermined,73,2.46,248.0 °,NaN,NaN,0,93
31,1514876400,2018-01-02 07:00:00+00:00,28800,30.48 Celcius,NaN,26.21 C,37.48 C,28.02,31.29 C,1005,undetermined,undetermined,78,1.75,247.0 °,0,NaN,NaN,83
32,1514880000,2018-01-02 08:00:00+00:00,28800,31.11 C,NaN,26.37 °C,38.11 C,29.02,32.58 C,1004,NaN,undetermined,76,1.53 m/s,244.0°,NaN,0,NaN,88.00%
33,1514883600,2018-01-02 09:00:00+00:00,28800,30.94 C,NaN,27.5,37.94,29.02,32.11 Celcius,1005,NaN,NaN,82,1,223.0 °,0,NaN,0,92
34,1514887200,2018-01-02 10:00:00+00:00,28800,29.23,NaN,27.23 C,36.23 C,28.02°C,29.9 C,1005.0 hPa,undetermined,NaN,89,0.23 m/s,125,0,NaN,NaN,93
35,1514890800,2018-01-02 11:00:00+00:00,28800,28.95 C,NaN,27.33,35.95,27.02 °C,30.04 C,1006,NaN,undetermined,91,0.93,142,0,NaN,0,95
36,1514894400,2018-01-02 12:00:00+00:00,28800,29.0 C,NaN,27.0 C,36.0°C,26.02 C,30.12°C,1007,unsettled,undetermined,89,0.75 m/s,137.0°,NaN,NaN,0,99.00%
37,1514898000,2018-01-02 13:00:00+00:00,28800,28.95,missing,27.14 C,35.95,26.02,30.19°C,1008,undetermined,NaN,90.00%,1.22,209.0°,0,NaN,no_snow,100.00%
38,1514901600,2018-01-02 14:00:00+00:00,28800,27.89 C,NaN,26.47,33.74 C,26.02,29.19 C,1008,undetermined,NaN,92,1.35,220.0 °,0,0 milimeter,NaN,100.00%
39,1514905200,2018-01-02 15:00:00+00:00,28800,27.16 C,NaN,26.29 C,31.79,25.02,28.52,1008,NaN,NaN,95,1.47m/s,211.0°,NaN,NaN,0,100
40,1514908800,2018-01-02 16:00:00+00:00,28800,27.03 C,NaN,25.98,31.26,25.02 C,28.03 C,1008,undetermined,undetermined,94,1.72,196.0°,0,0,0,100
41,1514912400,2018-01-02 17:00:00+00:00,28800,26.59 Celcius,-1m,25.9,26.59,25.49,27.96 C,1008.0hPa,undetermined,NaN,96,1.54 m/s,193,NaN,0,NaN,100
42,1514916000,2018-01-02 18:00:00+00:00,28800,26.35 C,NaN,25.66 C,26.35,25.42,27.94,1007,NaN,NaN,96,1.5,217.0°,NaN,NaN,0,100.00%
43,1514919600,2018-01-02 19:00:00+00:00,28800,25.93°C,NaN,25.42°C,27.11,24.95,27.93 C,1007,NaN,not_recorded,97,1.44,235.0°,NaN,NaN,0,100
44,1514923200,2018-01-02 20:00:00+00:00,28800,25.73 C,NaN,25.22,26.89,24.81,27.74 C,1007,undetermined,NaN,97,1.25 m/s,223.0°,NaN,NaN,0,100
45,1514926800,2018-01-02 21:00:00+00:00,28800,25.76°C,NaN,25.25 °C,26.92,24.75°C,27.56 C,1008.0 hPa,undetermined,NaN,97,1.65 m/s,203.0°,no_rain,0,0,99.00%
46,1514930400,2018-01-02 22:00:00+00:00,28800,26.66°C,NaN,25.07,26.66 C,26.08,27.45,1008,undetermined,NaN,91,1.56,202.0°,NaN,0,NaN,99
47,1514934000,2018-01-02 23:00:00+00:00,28800,26.88,NaN,25.1,30.39,26.02,27.39,1009,NaN,NaN,90,1.8m/s,206.0 °,no_rain,0,NaN,98
48,1514937600,2018-01-03 00:00:00+00:00,28800,27.1 C,NaN,24.94,30.8°C,26.57,27.83,1009,undetermined,NaN,88,1.4 m/s,194,NaN,NaN,0,100.00%
49,1514941200,2018-01-03 01:00:00+00:00,28800,26.78 Celcius,NaN,25.19 °C,30.21°C,26.24,28.04 C,1010.0 hPa,undetermined,NaN,91,1.19,202,0,NaN,0,100

## Cleaning Feature 'Temp'

Kita ekstrak angkanya dari string. 

Ini fungsinya bisa dipake lagi

In [58]:
# Function to extract numeric values and convert to float
def clean_and_convert_temperature(temperature_str):
    if temperature_str is np.nan:
        return None
    
    # Use regular expressions to extract numeric values
    temperature_str = temperature_str.replace(',', '.')  # Replace comma with period (if present)
    numeric_part = re.search(r'[\d.]+', temperature_str)
    
    if numeric_part:
        numeric_value = float(numeric_part.group())
        return numeric_value
    else:
        return None

# Apply the cleaning and conversion function to the column
df_train['temp'] = df_train['temp'].apply(clean_and_convert_temperature)
df_test['temp'] = df_test['temp'].apply(clean_and_convert_temperature)

## Cleaning Feature 'Visibility'

In [59]:
df_train.visibility.value_counts()

unrecognized    4352
-1m             4349
unknown         4326
-1km            4278
unidentified    4263
-1 km           4263
-1              4257
                4241
undefined       4238
-1 m            4234
missing         4165
empty           4146
Name: visibility, dtype: int64

Ini maksudnya gimana bjir, skip dulu deh

## Cleaning Feature 'd_point, feels, min_temp, max_temp'

Ini mirip sama yg temp jd sekalian aja pake fungsi dari temp

In [60]:
# Cleaning d_point
df_train['d_point'] = df_train['d_point'].apply(clean_and_convert_temperature)
df_test['d_point'] = df_test['d_point'].apply(clean_and_convert_temperature)

# Cleaning feels
df_train['feels'] = df_train['feels'].apply(clean_and_convert_temperature)
df_test['feels'] = df_test['feels'].apply(clean_and_convert_temperature)

# Cleaning min_temp
df_train['min_temp'] = df_train['min_temp'].apply(clean_and_convert_temperature)
df_test['min_temp'] = df_test['min_temp'].apply(clean_and_convert_temperature)

# Cleaning max_temp
df_train['max_temp'] = df_train['max_temp'].apply(clean_and_convert_temperature)
df_test['max_temp'] = df_test['max_temp'].apply(clean_and_convert_temperature)

## Cleaning Feature 'prssr'

Intinya diambil angkanya, ternyata simple bjir

In [61]:
df_train['prssr'] = df_train['prssr'].str.extract(r'(\d+\.\d+|\d+)').astype(float)
df_test['prssr'] = df_test['prssr'].str.extract(r'(\d+\.\d+|\d+)').astype(float)

## Cleaning feature 'sea_level' and 'ground_level'

In [62]:
df_train.sea_level.value_counts()

undetermined     154582
-1                 4890
unestablished      4823
unsettled          4809
not_recorded       4804
not-recorded       4803
unknown            4792
not recorded       4735
unspecified        4726
Name: sea_level, dtype: int64

In [63]:
df_test.sea_level.value_counts()

undetermined     22177
not-recorded       723
unknown            693
unestablished      691
unspecified        691
not_recorded       689
not recorded       688
-1                 677
unsettled          665
Name: sea_level, dtype: int64

In [64]:
df_train.grnd_level.value_counts()

undetermined     148814
not recorded       5615
not_recorded       5579
unspecified        5537
-1                 5511
unsettled          5497
not-recorded       5480
unknown            5443
unestablished      5443
Name: grnd_level, dtype: int64

In [65]:
df_test.grnd_level.value_counts()

undetermined     21491
unspecified        840
unestablished      824
unsettled          810
not recorded       795
not_recorded       785
-1                 777
unknown            776
not-recorded       768
Name: grnd_level, dtype: int64

Intinya datanya gaada ga sih ?! // kena preng

## Cleaning feature 'hum'

Disini datanya ada yg pake persen (%), jd mari lah

In [66]:
df_train['hum'] = df_train['hum'].str.extract(r'(\d+\.\d+|\d+)').astype(float)
df_test['hum'] = df_test['hum'].str.extract(r'(\d+\.\d+|\d+)').astype(float)

## Cleaning feature 'wind_spd'

In [67]:
df_train['wind_spd'] = df_train['wind_spd'].str.extract(r'(\d+\.\d+)').astype(float)
df_test['wind_spd'] = df_test['wind_spd'].str.extract(r'(\d+\.\d+)').astype(float)

## Cleaning feature 'wind_deg'

In [68]:
df_train['wind_deg'] = df_train['wind_deg'].str.replace('[^0-9.]', '', regex=True).astype(float)
df_test['wind_deg'] = df_test['wind_deg'].str.replace('[^0-9.]', '', regex=True).astype(float)

## Cleaning label 'rain_1h'

In [69]:
# Replace 'zero' with '0'
df_train['rain_1h'] = df_train['rain_1h'].replace('zero', '0')

# Replace all whitespace characters with '0'
df_train['rain_1h'] = df_train['rain_1h'].str.replace(r'\s+', '0', regex=True)

# Replace all to numeric
df_train['rain_1h'] = df_train['rain_1h'].str.extract(r'(-?\d+\.\d+|\d+)').astype(float)

### Cleaning feature 'rain_3h', 'snow_1h', 'snow_3h'

In [70]:
df_train.rain_3h.value_counts()

0              125413
no-rain          7553
0 milimeter      7484
volume:0         7483
nol              7465
0mm              7445
no_rain          7422
volume:zero      7405
0 mm             7401
zero             7258
Name: rain_3h, dtype: int64

In [71]:
df_test.rain_3h.value_counts()

0              18166
zero            1149
no_rain         1100
0 mm            1091
volume:0        1086
0 milimeter     1074
nol             1057
volume:zero     1051
0mm             1037
no-rain         1025
1                  3
0.25               2
Name: rain_3h, dtype: int64

In [72]:
df_train.snow_1h.value_counts()

0              145509
0 milimeter      5392
no-snow          5328
zero             5301
volume:zero      5263
0 mm             5252
nol              5191
volume:0         5165
0mm              5164
no_snow          5131
Name: snow_1h, dtype: int64

In [73]:
df_test.snow_1h.value_counts()

0              20972
no_snow          783
zero             754
no-snow          744
0 milimeter      740
nol              739
volume:0         739
0mm              739
volume:zero      734
0 mm             722
Name: snow_1h, dtype: int64

In [74]:
df_train.snow_3h.value_counts()

0              139397
zero             6069
nol              6039
0 mm             5989
no-snow          5896
volume:0         5880
0mm              5874
0 milimeter      5872
no_snow          5843
volume:zero      5840
Name: snow_3h, dtype: int64

In [75]:
df_test.snow_3h.value_counts()

0              20173
0 milimeter      899
no_snow          895
no-snow          876
volume:zero      864
0mm              862
zero             826
volume:0         816
0 mm             806
nol              786
Name: snow_3h, dtype: int64

Homto gaje lagi

## Cleaning feature 'clouds'

In [76]:
df_train['clouds'] = df_train['clouds'].str.replace('[^0-9.]', '', regex=True).astype(float)
df_test['clouds'] = df_test['clouds'].str.replace('[^0-9.]', '', regex=True).astype(float)

## Cek terakhir

In [77]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341880 entries, 0 to 341879
Data columns (total 20 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   datetime      341880 non-null  int64
 1   datetime_iso  341880 non-null  datetime64[ns, UTC]
 2   time-zone     341880 non-null  int64
 3   temp          341880 non-null  float64
 4   visibility    51112 non-null   object
 5   d_point       341880 non-null  float64
 6   feels         341880 non-null  float64
 7   min_temp      341880 non-null  float64
 8   max_temp      341880 non-null  float64
 9   prssr         341880 non-null  float64
 10  sea_level     192964 non-null  object
 11  grnd_level    192919 non-null  object
 12  hum           341880 non-null  float64
 13  wind_spd      339654 non-null  float64
 14  wind_deg      341880 non-null  float64
 15  rain_1h       341880 non-null  float64
 16  rain_3h       192329 non-null  object
 17  snow_1h       192696 non-null  object
 18  snow_3h       192699 non-null  object
 19  clouds        341880 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(11), int64(2), object(6)
memory usage: 52.2+ MB

In [78]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49368 entries, 0 to 49367
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   datetime      49368 non-null  int64
 1   datetime_iso  49368 non-null  datetime64[ns, UTC]
 2   time-zone     49368 non-null  int64
 3   temp          49368 non-null  float64
 4   visibility    7533 non-null   object
 5   d_point       49367 non-null  float64
 6   feels         49368 non-null  float64
 7   min_temp      49368 non-null  float64
 8   max_temp      49368 non-null  float64
 9   prssr         49368 non-null  float64
 10  sea_level     27694 non-null  object
 11  grnd_level    27866 non-null  object
 12  hum           49368 non-null  float64
 13  wind_spd      49034 non-null  float64
 14  wind_deg      49368 non-null  float64
 15  rain_3h       27841 non-null  object
 16  snow_1h       27666 non-null  object
 17  snow_3h       27803 non-null  object
 18  clouds        49368 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(10), int64(2), object(6)
memory usage: 7.2+ MB

Data siap dipake nih bang

## Save ke csv

In [79]:
df_train.to_csv('./dataset/train_cleaned.csv', index=False)
df_test.to_csv('./dataset/test_cleaned.csv', index=False)

# Kesimpulan:

- Data numeris yang awalnya bertipe data objek, sudah jadi float
- Data yang formatnya belum sama, sudah disamakan
- Buat feature yang masih bertipe object, itu karena pada dasarnya = 0 lol, tapiii karena ini datanya sintesis, bisa aja masih ada korelasinya
- Data disimpan di train_cleaned.csv dan test_cleaned.csv